export const ordersData = [
  {
    id: "ORDER-100",
    trackingNumber: "ORDER-100",
    customer: "Om",
    pickup: "Satara",
    delivery: "Raigad",
    sourceHub: "Satara Hub",
    destinationHub: null,
    distance: "100 km",
    distanceKm: 100,
    weight: "2.5 kg",
    packageWeight: 2.5,
    packageSize: "SMALL",
    deliveryType: "STANDARD",
    amount: 45,
    price: 45,
    status: "CREATED",
  },

  {
    id: "ORDER-101",
    trackingNumber: "ORDER-101",
    customer: "Om Kharmate",
    pickup: "Satara",
    delivery: "Raigad",
    sourceHub: "Satara Hub",
    destinationHub: null,
    distance: "100 km",
    distanceKm: 100,
    weight: "2.5 kg",
    packageWeight: 2.5,
    packageSize: "SMALL",
    deliveryType: "STANDARD",
    amount: 45,
    price: 45,
    status: "PICKUP_ASSIGNED",
  },

  {
    id: "ORDER-102",
    trackingNumber: "ORDER-102",
    customer: "Sarah Khan",
    pickup: "Kolhapur",
    delivery: "Satara",
    sourceHub: "Kolhapur Hub",
    destinationHub: "Satara Hub",
    distance: "150 km",
    distanceKm: 150,
    weight: "1.8 kg",
    packageWeight: 1.8,
    packageSize: "SMALL",
    deliveryType: "EXPRESS",
    amount: 52,
    price: 52,
    status: "PICKED_UP",
  },

  {
    id: "ORDER-103",
    trackingNumber: "ORDER-103",
    customer: "Rohan Patil",
    pickup: "Satara Hub",
    delivery: "Pune Hub",
    sourceHub: "Satara Hub",
    destinationHub: "Pune Hub",
    distance: "120 km",
    distanceKm: 120,
    weight: "3.2 kg",
    packageWeight: 3.2,
    packageSize: "MEDIUM",
    deliveryType: "STANDARD",
    amount: 90,
    price: 90,
    status: "AT_SOURCE_HUB",
  },

  {
    id: "ORDER-104",
    trackingNumber: "ORDER-104",
    customer: "Anjali Deshmukh",
    pickup: "Satara Hub",
    delivery: "Pune Hub",
    sourceHub: "Satara Hub",
    destinationHub: "Pune Hub",
    distance: "120 km",
    distanceKm: 120,
    weight: "3.5 kg",
    packageWeight: 3.5,
    packageSize: "MEDIUM",
    deliveryType: "STANDARD",
    amount: 95,
    price: 95,
    status: "IN_TRANSIT",
  },

  {
    id: "ORDER-105",
    trackingNumber: "ORDER-105",
    customer: "Anjali Deshmukh",
    pickup: "Pune Hub",
    delivery: "Mumbai Hub",
    sourceHub: "Pune Hub",
    destinationHub: "Mumbai Hub",
    distance: "140 km",
    distanceKm: 140,
    weight: "4.5 kg",
    packageWeight: 4.5,
    packageSize: "LARGE",
    deliveryType: "STANDARD",
    amount: 120,
    price: 120,
    status: "AT_DESTINATION_HUB",
  },

  {
    id: "ORDER-106",
    trackingNumber: "ORDER-106",
    customer: "Nikhil Joshi",
    pickup: "Mumbai Hub",
    delivery: "Andheri West",
    sourceHub: "Mumbai Hub",
    destinationHub: "Mumbai Hub",
    distance: "20 km",
    distanceKm: 20,
    weight: "1.2 kg",
    packageWeight: 1.2,
    packageSize: "SMALL",
    deliveryType: "EXPRESS",
    amount: 30,
    price: 30,
    status: "OUT_FOR_DELIVERY",
  },

  {
    id: "ORDER-107",
    trackingNumber: "ORDER-107",
    customer: "Om Mane",
    pickup: "123 Vaduj, Satara",
    delivery: "45 Ram Charan, Raigad",
    sourceHub: "Satara Hub",
    destinationHub: "Raigad Hub",
    distance: "100 km",
    distanceKm: 100,
    weight: "2.5 kg",
    packageWeight: 2.5,
    packageSize: "SMALL",
    deliveryType: "STANDARD",
    amount: 45,
    price: 45,
    status: "DELIVERED",
  },
];
