export const ordersData = [
  {
    id: "ORDER-100",
    customer: "Om ",
    pickup: "Satara",
    delivery: "Raigad",
    distance: "100 km",
    weight: "2.5 kg",
    amount: 45,
    status: "CREATED",
  },
  {
    id: "ORDER-101",
    customer: "Om Kharmate",
    pickup: "Satara",
    delivery: "Raigad",
    distance: "100 km",
    weight: "2.5 kg",
    amount: 45,
    status: "CREATED",
  },
  {
    id: "ORDER-102",
    customer: "Sarah Khan",
    pickup: "Kolhapur",
    delivery: "Satara",
    distance: "150 km",
    weight: "1.8 kg",
    amount: 52,
    status: "PICKED_UP",
  },
  {
    id: "ORDER-103",
    customer: "Rohan Patil",
    pickup: "Satara Hub",
    delivery: "Pune Hub",
    distance: "120 km",
    weight: "3.2 kg",
    amount: 90,
    status: "AT_SOURCE_HUB",
  },
  {
    id: "ORDER-104",
    customer: "Anjali Deshmukh",
    pickup: "Pune Hub",
    delivery: "Mumbai",
    distance: "140 km",
    weight: "4.5 kg",
    amount: 120,
    status: "AT_DESTINATION_HUB",
  },
];
