pipeline {
    agent any

    environment {
        IMAGE_NAME = "react-frontend"
        IMAGE_TAG  = "latest"
        CONTAINER_NAME = "react-frontend"
    }

    stages {

        stage('Checkout Code') {
            steps {
                git branch: 'main',
                    url: 'https://github.com/CourierWala/frontend.git'
            }
        }

        stage('Build Docker Image') {
            steps {
                sh '''
                  docker build -t $IMAGE_NAME:$IMAGE_TAG .
                '''
            }
        }

        stage('Run Container') {
            steps {
                sh '''
                  docker stop $CONTAINER_NAME || true
                  docker rm $CONTAINER_NAME || true

                  docker run -d \
                    --name $CONTAINER_NAME \
                    -p 80:80 \
                    $IMAGE_NAME:$IMAGE_TAG
                '''
            }
        }
    }

    post {
        success {
            echo "Frontend deployed successfully 🚀"
        }
        failure {
            echo "Frontend pipeline failed ❌"
        }
    }
}
